### ISSUE TITLE
HEAD / failed: (403)

### ISSUE THREAD

**Issue by nielll** [dom111/webdav-js#52]
Hi dom,

I have an error occuring after basic login. Of course, when I head to the webdav path, nginx will show me the 403 error page and a basic login window. I log in and afterwards it looks like this: ![image](https://niel.site/share/files/image.png)

Even thought the error appears, I am able to create a new directory but upload does not work, it through same error.

browser console: webdav-min.js:1 HEAD / net::ERR_ABORTED 403

**Comment by dom111** [comment]
Hey Niel, sorry to hear that... 403 is weird indeed. The toast appears to show that the HEAD request was forbidden too. I've not experimented much with nginx's WebDAV module, do you have a basic setup you could easily share with me that recreates the problem? I'll try and create a example config/docker-compose for nginx this week if I get time if not.

Thanks for the report!

**Comment by nielll** [comment]
Thx for your help dom,

In my server setup I am using Plesk, where nginx and Apache work in tandem, with Apache serving dynamic content and nginx being used as a proxy serving static content.

So, webdav is running under apache2 and maybe I have to set header now in nginx, as I didnt have to set before. But I am really not experienced at all. Docker is also disabled in my vps :/

Greetings

**Comment by dom111** [comment]
Thanks for the extra info. I'm guessing this happened only when updating to the latest version. which is a shame... The underlying mechanism should be the same, but it should be possible to bind to a specific version whilst I investigate this (you can run `build/examples-tag.sh 1.1.0` which should generate fixed version configs at 1.1.0) but I'd be really interested in finding out if I can avoid this problem in the app directly so any configs you can safely share for nginx and/or Apache would be awesome.

**Comment by dom111** [comment]
I've just pushed to a test branch which disables `HEAD` requests (if `data-disable-check` attribute exists on the page - so you'll need the updated `header.html` as well as source files). It's only a rough branch (and apparently I need to sort out the tests!) but would you be able to take a quick look and see if this fixes your problem when you have time please?

Thanks!

**Comment by nielll** [comment]
Hi dom,

> Thanks for the extra info. I'm guessing this happened only when updating to the latest version. 

yes, you are right!

> I've just pushed to a test branch which disables HEAD requests (if data-disable-check attribute exists on the page - so you'll need the updated header.html as well as source files). It's only a rough branch (and apparently I need to sort out the tests!) but would you be able to take a quick look and see if this fixes your problem when you have time please?

I tested it but it is still the same. I double checked it, also tested again with the old webdav-js.min (https://github.com/dom111/webdav-js/blob/82dce1a51f8810ba219ee6cb2b7fb04a5c89c015/src/webdav-min.js), which worked for me again. 

greets

**Comment by nielll** [comment]
I just saw that I forgot to set the attribut. It works by the way. :)

**Comment by dom111** [comment]
Oh great! I'm glad this works! I'll add in some tests for this and get it merged to master in the next week or so. Thanks for reporting!
